server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/main/**

        - id: vital-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/vital/**

        - id: iot-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/iot/**

        - id: chatbot-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/chat/**